---
- name: Check Disk Usage on Linux Machines
  hosts: all
  gather_facts: true
  tasks:
    - name: Execute 'df' command
      shell: df -h
      register: disk_usage_result
      changed_when: false

    - name: Display Disk Usage
      debug:
        var: disk_usage_result.stdout_lines
